import { Challenge } from './types'

const ALL: Challenge[] = [
  // == EASY ==
  { id:1,type:'multiple',difficulty:'easy',topic:'algorithms',
    question:'Which data structure follows FIFO?',
    options:['Stack','Queue','Array','Set'],correct:1,
    explanation:'Queue uses First-In-First-Out ordering.' },
  { id:2,type:'multiple',difficulty:'easy',topic:'web',
    question:'What does CSS stand for?',correct:1,
    options:['Computer Style Sheets','Cascading Style Sheets','Creative Style System','Colorful Style Sheets'],
    explanation:'CSS stands for Cascading Style Sheets.' },
  { id:3,type:'multiple',difficulty:'easy',topic:'javascript',
    question:'Which method adds an element to the END of an array?',
    options:['push()','pop()','shift()','unshift()'],correct:0,
    explanation:'push() appends elements to the end of an array.' },
  { id:4,type:'multiple',difficulty:'easy',topic:'general',
    question:'What does API stand for?',correct:0,
    options:['Application Programming Interface','Automated Program Integration','Application Process Integration','Advanced Programming Interface'],
    explanation:'API allows different software to communicate.' },
  { id:5,type:'multiple',difficulty:'easy',topic:'web',
    question:'Which HTML tag creates a hyperlink?',
    options:['<link>','<a>','<href>','<url>'],correct:1,
    explanation:'The <a> tag defines a hyperlink.' },
  { id:6,type:'multiple',difficulty:'easy',topic:'databases',
    question:'What does SQL stand for?',correct:1,
    options:['Simple Query Language','Structured Query Language','Standard Query Logic','Sequential Query Language'],
    explanation:'SQL is the standard for relational databases.' },
  { id:7,type:'multiple',difficulty:'easy',topic:'algorithms',
    question:'Which data structure follows LIFO?',
    options:['Queue','Stack','List','Tree'],correct:1,
    explanation:'Stack uses Last-In-First-Out ordering.' },
  { id:8,type:'multiple',difficulty:'easy',topic:'python',
    question:'What is the file extension for Python?',
    options:['.js','.py','.java','.rb'],correct:1,
    explanation:'Python files use the .py extension.' },
  { id:9,type:'multiple',difficulty:'easy',topic:'general',
    question:'What does git commit do?',correct:1,
    options:['Delete files','Save changes to local repo','Push to remote','Create a branch'],
    explanation:'git commit saves staged changes to the local repository.' },
  { id:10,type:'multiple',difficulty:'easy',topic:'javascript',
    question:'Which parses a JSON string?',correct:1,
    options:['JSON.stringify()','JSON.parse()','JSON.convert()','JSON.toObject()'],
    explanation:'JSON.parse() converts a JSON string to an object.' },
  { id:11,type:'fill-blank',difficulty:'easy',topic:'javascript',
    question:'Complete the code to print to console:',
    code:'console.___("Hello World");',correct:0,
    options:['log','print','write','echo'],
    explanation:'console.log() prints to the browser console.' },
  { id:12,type:'fill-blank',difficulty:'easy',topic:'javascript',
    question:'Fill the missing keyword to declare a constant:',
    code:'___ PI = 3.14;',correct:0,
    options:['const','let','var','static'],
    explanation:'const declares a constant (immutable) variable.' },
  { id:13,type:'output',difficulty:'easy',topic:'javascript',
    question:'What does this print?',
    code:'console.log(2 + 3);',correct:2,
    options:['23','6','5','8'],
    explanation:'2 + 3 evaluates to 5.' },
  { id:14,type:'output',difficulty:'easy',topic:'javascript',
    question:'What does this print?',
    code:'console.log("Hi" + " there");',correct:1,
    options:['Hi there','Hi there','Hi+there','Error'],
    explanation:'String concatenation joins "Hi" and " there".' },
  { id:15,type:'spot-bug',difficulty:'easy',topic:'javascript',
    question:'What is wrong here?',
    code:'let x = 5\nconsole.log(X);',correct:2,
    options:['Missing semicolon','Wrong quote type','Variable name typo','console is undefined'],
    explanation:'X is not defined; JavaScript is case-sensitive, use x.' },
  { id:16,type:'fill-blank',difficulty:'easy',topic:'python',
    question:'Complete the Python print statement:',
    code:'print(___ World")',correct:1,
    options:['"Hello','\'Hello','Hello','"hello'],
    explanation:'Strings in Python use quotes: print("Hello World").' },
  { id:17,type:'output',difficulty:'easy',topic:'python',
    question:'What does this Python print?',
    code:'print(type(42))',correct:2,
    options:['<class \'str\'>','int','<class \'int\'>','number'],
    explanation:'type(42) returns <class \'int\'>.' },
  { id:18,type:'spot-bug',difficulty:'easy',topic:'web',
    question:'What is wrong?',
    code:'<img src="photo.jpg">',correct:3,
    options:['Missing alt text','src is wrong','Wrong tag','Nothing - it is valid'],
    explanation:'Valid HTML, but missing alt text for accessibility.' },
  { id:19,type:'fill-blank',difficulty:'easy',topic:'databases',
    question:'Complete the SQL query to select all:',
    code:'SELECT ___ FROM users',correct:1,
    options:['ALL','*','EVERYTHING','ALL COLUMNS'],
    explanation:'SELECT * FROM users selects all columns.' },
  { id:20,type:'output',difficulty:'easy',topic:'algorithms',
    question:'What is the result?',code:'2 + 3 * 4',correct:0,
    options:['14','20','24','9'],
    explanation:'Multiplication first: 3*4=12, then 2+12=14.' },

  // == MEDIUM ==
  { id:21,type:'multiple',difficulty:'medium',topic:'javascript',
    question:'What does typeof null return?',
    options:['null','undefined','object','boolean'],correct:2,
    explanation:'typeof null returns "object" (a legacy JS bug).' },
  { id:22,type:'fill-blank',difficulty:'medium',topic:'javascript',
    question:'Complete the arrow function:',
    code:'const add = (a,b) ___ a + b;',correct:0,
    options:['=>','->','=>>',':'],
    explanation:'Arrow functions use => syntax: (a,b) => a + b.' },
  { id:23,type:'output',difficulty:'medium',topic:'javascript',
    question:'What does this print?',
    code:'console.log(0.1 + 0.2 === 0.3)',correct:3,
    options:['true','false','0','false (floating point)'],
    explanation:'0.1+0.2=0.3000000004 due to floating point precision.' },
  { id:24,type:'spot-bug',difficulty:'medium',topic:'javascript',
    question:'What is the bug?',
    code:'if (x = 5) { console.log("yes"); }',correct:0,
    options:['Single = instead of ===','Missing semicolon','Missing braces','x not defined'],
    explanation:'x = 5 is assignment, not comparison. Use ===.' },
  { id:25,type:'multiple',difficulty:'medium',topic:'python',
    question:'Which creates a list in Python?',
    options:['[]','{}','()','<>'],correct:0,
    explanation:'Square brackets [] create a list in Python.' },
  { id:26,type:'fill-blank',difficulty:'medium',topic:'python',
    question:'Complete the list comprehension:',
    code:'squares = [x__2 for x in range(5)]',correct:1,
    options:['^','**','pow','*'],
    explanation:'** is the exponent operator in Python.' },
  { id:27,type:'output',difficulty:'medium',topic:'python',
    question:'What does this print?',
    code:'print(len("hello"))',correct:2,
    options:['4','6','5','3'],
    explanation:'len("hello") returns 5 characters.' },
  { id:28,type:'spot-bug',difficulty:'medium',topic:'web',
    question:'What is wrong with this CSS?',
    code:'.box {\n  color: red;\n  background-color: blue;\n}',correct:3,
    options:['Missing semicolon','Wrong selector','color is invalid','Nothing - it is valid'],
    explanation:'The CSS is syntactically correct.' },
  { id:29,type:'multiple',difficulty:'medium',topic:'databases',
    question:'Which SQL clause filters rows?',
    options:['ORDER BY','GROUP BY','WHERE','HAVING'],correct:2,
    explanation:'WHERE filters rows before aggregation.' },
  { id:30,type:'fill-blank',difficulty:'medium',topic:'algorithms',
    question:'What is the time complexity of binary search?',
    code:'O(___ n)',correct:0,
    options:['log','n','n^2','2^n'],
    explanation:'Binary search runs in O(log n) time.' },
  { id:31,type:'output',difficulty:'medium',topic:'javascript',
    question:'What does this print?',
    code:'console.log(typeof 42)',correct:1,
    options:['number','number','integer','float'],
    explanation:'typeof 42 returns "number".' },
  { id:32,type:'spot-bug',difficulty:'medium',topic:'general',
    question:'What is wrong?',
    code:'git pish origin main',correct:0,
    options:['Typo in command','Wrong branch','Missing flag','Nothing'],
    explanation:'"pish" should be "push": git push origin main.' },
  { id:33,type:'multiple',difficulty:'medium',topic:'javascript',
    question:'What is closure in JS?',
    options:['A syntax error','Function with access to outer scope','A built-in method','A loop type'],
    correct:1,
    explanation:'A closure is a function that retains access to its lexical scope.' },
  { id:34,type:'fill-blank',difficulty:'medium',topic:'algorithms',
    question:'Complete Big O of linear search:',
    code:'O(___)',correct:2,
    options:['1','log n','n','n^2'],
    explanation:'Linear search checks each element: O(n).' },
  { id:35,type:'output',difficulty:'medium',topic:'javascript',
    question:'What does this print?',
    code:'console.log(Boolean(0))',correct:2,
    options:['true','1','false','undefined'],
    explanation:'0 is falsy in JavaScript, so Boolean(0) is false.' },
  { id:36,type:'spot-bug',difficulty:'medium',topic:'python',
    question:'What is the bug?',
    code:'def add(x, y):\n  return x + y\nprint(add(5))',correct:1,
    options:['Wrong indentation','Missing argument','No return','Typo in print'],
    explanation:'add expects 2 args, only 1 provided.' },

  // == HARD ==
  { id:37,type:'multiple',difficulty:'hard',topic:'javascript',
    question:'What does Promise.all() do?',
    options:['Runs promises sequentially','Resolves when all promises resolve','Rejects on first resolve','Creates a new promise'],
    correct:1,
    explanation:'Promise.all() resolves when all promises in the iterable resolve.' },
  { id:38,type:'fill-blank',difficulty:'hard',topic:'javascript',
    question:'Complete the async function:',
    code:'async function getData() {\n  return ___ fetch("/api");\n}',correct:0,
    options:['await','then','wait','async'],
    explanation:'await pauses execution until the Promise settles.' },
  { id:39,type:'output',difficulty:'hard',topic:'javascript',
    question:'What does this print?',
    code:'console.log([1,2,3].map(x => x * 2))',correct:1,
    options:['[1,2,3]','[2,4,6]','[2,3,4]','[1,4,9]'],
    explanation:'map doubles each element: [2,4,6].' },
  { id:40,type:'spot-bug',difficulty:'hard',topic:'algorithms',
    question:'What is the bug?',
    code:'function fib(n) {\n  if (n <= 1) return n;\n  return fib(n-1) + fib(n-1);\n}',correct:2,
    options:['Wrong base case','Missing return','Incorrect recursion','Stack overflow'],
    explanation:'Should be fib(n-1) + fib(n-2), not two fib(n-1) calls.' },
  { id:41,type:'multiple',difficulty:'hard',topic:'python',
    question:'What is a decorator in Python?',
    options:['A design pattern','Function that modifies another function','A class method','A type hint'],
    correct:1,
    explanation:'A decorator takes a function and extends its behavior.' },
  { id:42,type:'fill-blank',difficulty:'hard',topic:'databases',
    question:'Complete the JOIN:',
    code:'SELECT * FROM users ___ JOIN orders ON users.id = orders.user_id',correct:1,
    options:['INNER','INNER','LEFT','RIGHT'],
    explanation:'INNER JOIN returns matching rows from both tables.' },
  { id:43,type:'output',difficulty:'hard',topic:'general',
    question:'What is the output?',
    code:'git log --oneline -3',correct:3,
    options:['Last 3 commits','3 branches','3 files changed','3 most recent commits (one line each)'],
    explanation:'--oneline shows one line per commit, -3 limits to 3.' },
  { id:44,type:'spot-bug',difficulty:'hard',topic:'web',
    question:'What is wrong?',
    code:'<div onclick="myFunction()">Click</div>\n// no myFunction defined anywhere',correct:0,
    options:['Function not defined','onclick is wrong','Missing parentheses','Nothing'],
    explanation:'myFunction is called but never defined, causing a ReferenceError.' },
  { id:45,type:'multiple',difficulty:'hard',topic:'algorithms',
    question:'What is the time complexity of Merge Sort?',
    options:['O(n)','O(n log n)','O(n^2)','O(log n)'],correct:1,
    explanation:'Merge Sort divides and conquers in O(n log n).' },
  { id:46,type:'fill-blank',difficulty:'hard',topic:'javascript',
    question:'Complete the reduce call to sum an array:',
    code:'[1,2,3].reduce((a,b) => ___)',correct:2,
    options:['a-b','a*b','a+b','b-a'],
    explanation:'reduce accumulates: a+b sums the array to 6.' },
  { id:47,type:'output',difficulty:'hard',topic:'python',
    question:'What does this print?',
    code:'print(list(range(0, 10, 3)))',correct:1,
    options:['[0,3,6,9]','[0,3,6,9]','[0,1,2,3,4,5,6,7,8,9]','[3,6,9]'],
    explanation:'range(0,10,3) generates 0,3,6,9.' },
  { id:48,type:'spot-bug',difficulty:'hard',topic:'javascript',
    question:'What is the bug in this React component?',
    code:'function App() {\n  const [count, setCount] = useState(0);\n  return <h1>{count}</h1>;\n}',
    options:['Missing import','count not used','setCount not called','Nothing wrong'],
    correct:0,
    explanation:'useState is not imported from React.' },
  { id:49,type:'multiple',difficulty:'hard',topic:'databases',
    question:'What is a LEFT JOIN?',
    options:['Only matching rows','All rows from left table','All rows from right table','All rows from both'],
    correct:1,
    explanation:'LEFT JOIN returns all rows from the left table, matched or not.' },
  { id:50,type:'output',difficulty:'hard',topic:'javascript',
    question:'What is the order of output?',
    code:'console.log("a");\nsetTimeout(() => console.log("b"), 0);\nconsole.log("c");',correct:3,
    options:['a,b,c','b,a,c','c,b,a','a,c,b'],
    explanation:'setTimeout runs after sync code: "a", then "c", then "b".' },
  { id:51,type:'fill-blank',difficulty:'hard',topic:'algorithms',
    question:'Complete quick sort recurrence:',
    code:'T(n) = T(k) + T(n-k-1) + O(___)',correct:2,
    options:['1','log n','n','n^2'],
    explanation:'The partition step of quicksort takes O(n).' },
  { id:52,type:'spot-bug',difficulty:'medium',topic:'general',
    question:'What is wrong?',
    code:'const http = require("fs");\nhttp.createServer()',correct:1,
    options:['require is wrong','Wrong module imported','Missing port','Nothing'],
    explanation:'fs is the filesystem module, not http. Use require("http").' },
  { id:53,type:'output',difficulty:'medium',topic:'javascript',
    question:'What does this print?',
    code:'console.log(!!"false")',correct:0,
    options:['true','false','"false"','undefined'],
    explanation:'!"false" is a non-empty string, which converts to true.' },
  { id:54,type:'fill-blank',difficulty:'easy',topic:'web',
    question:'Complete the HTML doctype:',
    code:'___DOCTYPE html>',correct:0,
    options:['<!','<?','<#','<%'],
    explanation:'HTML5 doctype is <!DOCTYPE html>.' },
  { id:55,type:'spot-bug',difficulty:'hard',topic:'python',
    question:'What is wrong?',
    code:'x = [1,2,3]\nx.add(4)\nprint(x)',correct:1,
    options:['print syntax','Lists have no add() method','Wrong variable','x not defined'],
    explanation:'Python lists use append(), not add().' },
  { id:56,type:'multiple',difficulty:'medium',topic:'algorithms',
    question:'Which is NOT a sorting algorithm?',
    options:['Merge Sort','Quick Sort','Binary Sort','Heap Sort'],correct:2,
    explanation:'There is no "Binary Sort". Binary search is search, not sort.' },
  { id:57,type:'fill-blank',difficulty:'hard',topic:'web',
    question:'Complete the CSS flex centering:',
    code:'display: flex;\njustify-content: center;\nalign-items: ___;',correct:1,
    options:['center','center','middle','flex-center'],
    explanation:'align-items: center vertically centers flex items.' },

  // === NEW CHALLENGES (58-100) ===

  // -- EASY --
  { id:58,type:'multiple',difficulty:'easy',topic:'javascript',
    question:'What does the === operator compare?',
    options:['Value only','Value and type','Type only','Reference'],correct:1,
    explanation:'=== checks both value and type without type coercion.' },
  { id:59,type:'multiple',difficulty:'easy',topic:'python',
    question:'What keyword defines a function in Python?',
    options:['func','define','def','function'],correct:2,
    explanation:'The def keyword declares a function in Python.' },
  { id:60,type:'multiple',difficulty:'easy',topic:'web',
    question:'Which HTTP method is used to retrieve data from a server?',
    options:['POST','PUT','GET','DELETE'],correct:2,
    explanation:'GET requests retrieve data from a specified resource.' },
  { id:61,type:'multiple',difficulty:'easy',topic:'databases',
    question:'Which SQL keyword is used to sort the result set?',
    options:['SORT','ORDER BY','GROUP BY','ARRANGE'],correct:1,
    explanation:'ORDER BY sorts results in ascending or descending order.' },
  { id:62,type:'fill-blank',difficulty:'easy',topic:'general',
    question:'Complete the binary AND operation:',
    code:'1 AND 0 = ___',correct:1,
    options:['1','0','true','false'],
    explanation:'In Boolean logic, 1 AND 0 evaluates to 0.' },
  { id:63,type:'fill-blank',difficulty:'easy',topic:'algorithms',
    question:'Complete the hash map set operation:',
    code:'map.___("key", value)',correct:0,
    options:['set','put','insert','add'],
    explanation:'Hash maps / dictionaries use set(key, value) to store entries.' },
  { id:64,type:'fill-blank',difficulty:'easy',topic:'javascript',
    question:'Fill the blank to get the length of an array:',
    code:'let len = arr.___',correct:0,
    options:['length','size','count','len'],
    explanation:'The .length property returns the number of elements in an array.' },
  { id:65,type:'fill-blank',difficulty:'easy',topic:'python',
    question:'Complete Python\'s membership test:',
    code:'if "a" ___ "abc":',correct:0,
    options:['in','contains','has','of'],
    explanation:'The in operator checks membership in Python.' },
  { id:66,type:'output',difficulty:'easy',topic:'web',
    question:'What does this CSS property do?',
    code:'color: red;',correct:0,
    options:['Changes text color to red','Changes background to red','Adds a red border','Makes the element red'],
    explanation:'The color property sets the foreground / text color.' },
  { id:67,type:'output',difficulty:'easy',topic:'databases',
    question:'What does this query return?',
    code:'SELECT COUNT(*) FROM users',correct:1,
    options:['All user records','The number of users','The first user','A list of counts'],
    explanation:'COUNT(*) returns the number of rows in the result set.' },
  { id:68,type:'output',difficulty:'easy',topic:'general',
    question:'What is the result of this expression?',
    code:'2 ** 3',correct:1,
    options:['6','8','5','9'],
    explanation:'** is exponentiation: 2 raised to the power of 3 is 8.' },
  { id:69,type:'spot-bug',difficulty:'easy',topic:'algorithms',
    question:'What is the bug in this code?',
    code:'function sum(a, b) {\n  return a + b;\n}\nconsole.log(sum(5));',correct:1,
    options:['Wrong function name','Missing second argument','No return value','console is not defined'],
    explanation:'sum expects 2 arguments but only 1 (5) is provided; b is undefined.' },
  { id:70,type:'spot-bug',difficulty:'easy',topic:'javascript',
    question:'What is wrong here?',
    code:'let obj = {name: "John"};\nconsole.log(obj.Name);',correct:1,
    options:['Syntax error','Property name is case-sensitive','Missing quotes around key','obj is not defined'],
    explanation:'JavaScript property names are case-sensitive; obj.Name is undefined, use obj.name.' },
  { id:71,type:'spot-bug',difficulty:'easy',topic:'algorithms',
    question:'What is the bug in this loop?',
    code:'for (i = 0; i < 5; i++) {\n  console.log(i);\n}',correct:0,
    options:['i is undeclared (implicit global)','Wrong loop condition','Missing semicolon','No bug'],
    explanation:'i is not declared with let/var/const, creating an implicit global variable.' },

  // -- MEDIUM --
  { id:72,type:'multiple',difficulty:'medium',topic:'javascript',
    question:'What does the bind() method return?',
    options:['A new function with a fixed this','The original function','An object literal','A promise'],
    correct:0,
    explanation:'bind() creates a new function with this permanently bound to the provided value.' },
  { id:73,type:'multiple',difficulty:'medium',topic:'python',
    question:'What does *args represent in a Python function definition?',
    options:['Keyword arguments dict','Variable number of positional args','Default parameter values','Decorator arguments'],
    correct:1,
    explanation:'*args collects extra positional arguments into a tuple.' },
  { id:74,type:'multiple',difficulty:'medium',topic:'web',
    question:'What does the z-index CSS property control?',
    options:['Zoom level','Stacking order of positioned elements','Z-axis rotation angle','Letter spacing'],
    correct:1,
    explanation:'z-index determines which positioned element appears on top.' },
  { id:75,type:'multiple',difficulty:'medium',topic:'databases',
    question:'Which SQL keyword removes duplicate rows from a result set?',
    options:['UNIQUE','DISTINCT','REMOVE','FILTER'],correct:1,
    explanation:'SELECT DISTINCT returns only unique rows, eliminating duplicates.' },
  { id:76,type:'fill-blank',difficulty:'medium',topic:'general',
    question:'Complete the hexadecimal color code for white:',
    code:'___FFFFFF',correct:0,
    options:['#','0x','&','$'],
    explanation:'In CSS, hex colors start with #: #FFFFFF is white.' },
  { id:77,type:'fill-blank',difficulty:'medium',topic:'algorithms',
    question:'Complete the stack push operation:',
    code:'stack.___(item)',correct:0,
    options:['push','add','append','insert'],
    explanation:'The standard stack operation to add an element is push().' },
  { id:78,type:'fill-blank',difficulty:'medium',topic:'javascript',
    question:'Complete the Promise constructor:',
    code:'const p = new Promise((___) => {\n  // async work\n});',correct:0,
    options:['resolve, reject','then, catch','success, error','done, fail'],
    explanation:'Promise constructor receives (resolve, reject) as executor parameters.' },
  { id:79,type:'fill-blank',difficulty:'medium',topic:'python',
    question:'Complete the file reading code:',
    code:'with open("file.txt") as f:\n  data = f.___()',correct:0,
    options:['read','write','load','get'],
    explanation:'f.read() reads the entire contents of the file.' },
  { id:80,type:'output',difficulty:'medium',topic:'web',
    question:'What does this CSS declaration do?',
    code:'display: none;',correct:0,
    options:['Hides the element (removes from flow)','Hides but preserves space','Shows the element','Causes a rendering error'],
    explanation:'display: none removes the element from the document flow entirely.' },
  { id:81,type:'output',difficulty:'medium',topic:'databases',
    question:'What does this query match?',
    code:'SELECT * FROM users WHERE name LIKE "J%"',correct:1,
    options:['Users whose name contains J','Users whose name starts with J','Users whose name ends with J','Users named exactly J'],
    explanation:'LIKE "J%" matches any name that begins with the letter J.' },
  { id:82,type:'output',difficulty:'medium',topic:'general',
    question:'What does this git command do?',
    code:'git branch feature-x',correct:1,
    options:['Switches to branch feature-x','Creates a new branch called feature-x','Deletes branch feature-x','Merges feature-x into current'],
    explanation:'git branch <name> creates a new branch without switching to it.' },
  { id:83,type:'spot-bug',difficulty:'medium',topic:'algorithms',
    question:'What is the bug in this recursive function?',
    code:'function factorial(n) {\n  if (n === 0) return 1;\n  return n * factorial(n - 1);\n}\nconsole.log(factorial(-1));',correct:2,
    options:['Wrong base case','Missing return statement','Infinite recursion (stack overflow)','console.log is not defined'],
    explanation:'factorial(-1) never reaches the base case n === 0, causing infinite recursion.' },
  { id:84,type:'spot-bug',difficulty:'medium',topic:'javascript',
    question:'What is wrong here?',
    code:'console.log(1.toString());',correct:0,
    options:['Syntax error (number literal needs parentheses)','toString is not a function','Works correctly','Wrong method name'],
    explanation:'1.toString() is a syntax error due to the parser. Use (1).toString() or 1..toString().' },
  { id:85,type:'spot-bug',difficulty:'medium',topic:'python',
    question:'What is the bug?',
    code:'d = {1: "a", 2: "b"}\nprint(d[3])',correct:1,
    options:['Syntax error','KeyError - key 3 does not exist','Wrong print function syntax','Braces should be brackets'],
    explanation:'d[3] raises KeyError because key 3 is not present in the dictionary.' },
  { id:86,type:'spot-bug',difficulty:'medium',topic:'general',
    question:'What is wrong with this terminal command?',
    code:'rm -rf /',correct:1,
    options:['Missing sudo prefix','Recursively deletes everything on the filesystem','Path does not exist','Nothing is wrong'],
    explanation:'rm -rf / recursively deletes all files and directories. Extremely dangerous.' },

  // -- HARD --
  { id:87,type:'multiple',difficulty:'hard',topic:'javascript',
    question:'What does Object.freeze() do?',
    options:['Makes an object immutable (no additions or changes)','Deletes the object from memory','Converts the object to JSON','Prevents garbage collection'],
    correct:0,
    explanation:'Object.freeze() prevents new properties from being added and existing ones from being modified.' },
  { id:88,type:'multiple',difficulty:'hard',topic:'python',
    question:'What does a @staticmethod do in Python?',
    options:['Creates a method not bound to instance or class','Makes the method return a constant','Prevents the method from being overridden','Caches the method result'],
    correct:0,
    explanation:'@staticmethod defines a method that does not receive an implicit first argument (self or cls).' },
  { id:89,type:'multiple',difficulty:'hard',topic:'web',
    question:'What is CORS in web development?',
    options:['A security mechanism that controls cross-origin HTTP requests','A CSS preprocessor','A JavaScript bundler','A database management system'],
    correct:0,
    explanation:'Cross-Origin Resource Sharing (CORS) is a browser security feature restricting cross-origin requests.' },
  { id:90,type:'fill-blank',difficulty:'hard',topic:'databases',
    question:'Complete the query to find the second highest salary:',
    code:'SELECT MAX(salary) FROM employees\nWHERE salary ___ (SELECT MAX(salary) FROM employees)',correct:0,
    options:['<','>','!=','<>'],
    explanation:'Using < with MAX finds the max salary less than the overall max, yielding the second highest.' },
  { id:91,type:'fill-blank',difficulty:'hard',topic:'general',
    question:'Complete the IPv4 loopback address:',
    code:'127.___.0.1',correct:0,
    options:['0','1','127','255'],
    explanation:'127.0.0.1 is the standard loopback IP address pointing to the local machine.' },
  { id:92,type:'fill-blank',difficulty:'hard',topic:'javascript',
    question:'Complete the try...catch block:',
    code:'try {\n  riskyCode();\n} ___ (err) {\n  console.error(err);\n}',correct:0,
    options:['catch','except','error','handle'],
    explanation:'JavaScript uses catch(err) after try to handle thrown exceptions.' },
  { id:93,type:'output',difficulty:'hard',topic:'python',
    question:'What does this print?',
    code:'print({1, 2, 3} & {2, 3, 4})',correct:0,
    options:['{2, 3}','{1, 2, 3, 4}','{1, 4}','Error'],
    explanation:'The & operator on sets returns the intersection: {2, 3}.' },
  { id:94,type:'output',difficulty:'hard',topic:'web',
    question:'What does this CSS achieve?',
    code:'position: fixed;\ntop: 0;\nleft: 0;',correct:0,
    options:['Positions the element relative to the viewport (stays on scroll)','Positions relative to the parent','Absolute positioning within container','Static default positioning'],
    explanation:'position: fixed pins the element to the viewport so it does not move when scrolling.' },
  { id:95,type:'output',difficulty:'hard',topic:'databases',
    question:'What does this SQL function return?',
    code:'SELECT COALESCE(NULL, NULL, "hello", NULL)',correct:1,
    options:['NULL','hello','Error','true'],
    explanation:'COALESCE returns the first non-NULL value in the list, which is "hello".' },
  { id:96,type:'output',difficulty:'hard',topic:'general',
    question:'What permissions does this command set?',
    code:'chmod 755 script.sh',correct:0,
    options:['Owner: rwx, Group: rx, Others: rx','Owner: rwx, Group: wx, Others: wx','Owner: rw, Group: r, Others: r','Owner: rwx, Group: rwx, Others: rx'],
    explanation:'755 gives the owner full (rwx) and group/others read+execute (rx) permissions.' },
  { id:97,type:'spot-bug',difficulty:'hard',topic:'algorithms',
    question:'What is the bug in this binary search?',
    code:'function binarySearch(arr, target) {\n  let left = 0, right = arr.length;\n  while (left < right) {\n    let mid = (left + right) / 2;\n    if (arr[mid] === target) return mid;\n    if (arr[mid] < target) left = mid + 1;\n    else right = mid;\n  }\n  return -1;\n}',correct:1,
    options:['Infinite loop on large arrays','Mid calculation can be a float (needs integer division)','Missing base case for empty array','No bug - correct implementation'],
    explanation:'(left + right) / 2 can result in a float; use Math.floor((left + right) / 2) for integer index.' },
  { id:98,type:'spot-bug',difficulty:'hard',topic:'python',
    question:'What is the bug in this function?',
    code:'def append_to(element, target=[]):\n  target.append(element)\n  return target',correct:0,
    options:['Default mutable argument is shared across calls','Syntax error on default parameter','append is not a list method','No bug'],
    explanation:'The default [] is created once and shared across all calls, causing unintended mutation.' },
  { id:99,type:'spot-bug',difficulty:'hard',topic:'web',
    question:'What is wrong with this CSS?',
    code:'.container {\n  display: flexbox;\n}',correct:0,
    options:['flexbox is not a valid display value (use flex)','Missing closing brace','container is a reserved word','No bug'],
    explanation:'The correct display value for a flex container is flex, not flexbox.' },
  { id:100,type:'spot-bug',difficulty:'hard',topic:'databases',
    question:'What is the problem with this SQL statement?',
    code:'DELETE FROM users',correct:0,
    options:['Deletes ALL rows (no WHERE clause - dangerous)','Syntax error - misspelled DELETE','FROM keyword is incorrect','No bug - correct statement'],
    explanation:'Without a WHERE clause, DELETE FROM users removes every row in the table.' },
]

const BY_ID = new Map<number, Challenge>()
ALL.forEach(c => BY_ID.set(c.id, c))

export function getChallengeById(id: number): Challenge | undefined {
  return BY_ID.get(id)
}

export function getRandomChallenge(usedIds: Set<number>, topic?: string, preferDifficulty?: string): Challenge {
  let pool = ALL
  if (topic) pool = ALL.filter(c => c.topic === topic)
  if (pool.length === 0) pool = ALL

  let available = pool
  if (preferDifficulty) {
    const preferred = pool.filter(c => c.difficulty === preferDifficulty && !usedIds.has(c.id))
    if (preferred.length > 0) available = preferred
  }

  const remaining = available.filter(c => !usedIds.has(c.id))
  if (remaining.length === 0) {
    usedIds.clear()
    return pool[Math.floor(Math.random() * pool.length)]
  }
  return remaining[Math.floor(Math.random() * remaining.length)]
}

export const TOPICS = [
  { id: 'general', label: 'General CS', description: 'Computer science fundamentals' },
  { id: 'javascript', label: 'JavaScript', description: 'JS, Node.js & frontend' },
  { id: 'python', label: 'Python', description: 'Python programming' },
  { id: 'web', label: 'Web Dev', description: 'HTML, CSS & HTTP' },
  { id: 'databases', label: 'Databases', description: 'SQL & data storage' },
  { id: 'algorithms', label: 'Algorithms', description: 'Data structures & complexity' },
] as const

export const TOTAL_CHALLENGES = ALL.length

export function getDailyChallenge(): Challenge {
  const today = new Date()
  const seed = today.getFullYear() * 10000 + (today.getMonth() + 1) * 100 + today.getDate()
  const idx = seed % ALL.length
  return ALL[idx]
}

export function isDailyCompleted(): boolean {
  const today = new Date().toISOString().slice(0, 10)
  try {
    return localStorage.getItem('code_daily_' + today) === 'done'
  } catch { return false }
}

export function markDailyCompleted() {
  const today = new Date().toISOString().slice(0, 10)
  try { localStorage.setItem('code_daily_' + today, 'done') } catch {}
}

const LB_KEY = 'code_leaderboard'
export function getLeaderboard(): { score: number; date: string }[] {
  try {
    return JSON.parse(localStorage.getItem(LB_KEY) || '[]')
  } catch { return [] }
}

export function addToLeaderboard(score: number) {
  const lb = getLeaderboard()
  lb.push({ score, date: new Date().toISOString().slice(0, 10) })
  lb.sort((a, b) => b.score - a.score)
  const top = lb.slice(0, 10)
  try { localStorage.setItem(LB_KEY, JSON.stringify(top)) } catch {}
}
