import { Challenge } from './types'

const ALL: Challenge[] = [
  // == EASY ==
  { id:1,type:'multiple',difficulty:'easy',topic:'algorithms',
    question:'Which data structure follows FIFO?',
    options:['Stack','Queue','Array','Set'],correct:1,
    explanation:'Queue uses First-In-First-Out ordering.' },
  { id:2,type:'multiple',difficulty:'easy',topic:'web',
    question:'What does CSS stand for?',correct:1,
    options:['Computer Style Sheets','Cascading Style Sheets','Creative Style System','Colorful Style Sheets'],
    explanation:'CSS stands for Cascading Style Sheets.' },
  { id:3,type:'multiple',difficulty:'easy',topic:'javascript',
    question:'Which method adds an element to the END of an array?',
    options:['push()','pop()','shift()','unshift()'],correct:0,
    explanation:'push() appends elements to the end of an array.' },
  { id:4,type:'multiple',difficulty:'easy',topic:'general',
    question:'What does API stand for?',correct:0,
    options:['Application Programming Interface','Automated Program Integration','Application Process Integration','Advanced Programming Interface'],
    explanation:'API allows different software to communicate.' },
  { id:5,type:'multiple',difficulty:'easy',topic:'web',
    question:'Which HTML tag creates a hyperlink?',
    options:['<link>','<a>','<href>','<url>'],correct:1,
    explanation:'The <a> tag defines a hyperlink.' },
  { id:6,type:'multiple',difficulty:'easy',topic:'databases',
    question:'What does SQL stand for?',correct:1,
    options:['Simple Query Language','Structured Query Language','Standard Query Logic','Sequential Query Language'],
    explanation:'SQL is the standard for relational databases.' },
  { id:7,type:'multiple',difficulty:'easy',topic:'algorithms',
    question:'Which data structure follows LIFO?',
    options:['Queue','Stack','List','Tree'],correct:1,
    explanation:'Stack uses Last-In-First-Out ordering.' },
  { id:8,type:'multiple',difficulty:'easy',topic:'python',
    question:'What is the file extension for Python?',
    options:['.js','.py','.java','.rb'],correct:1,
    explanation:'Python files use the .py extension.' },
  { id:9,type:'multiple',difficulty:'easy',topic:'general',
    question:'What does git commit do?',correct:1,
    options:['Delete files','Save changes to local repo','Push to remote','Create a branch'],
    explanation:'git commit saves staged changes to the local repository.' },
  { id:10,type:'multiple',difficulty:'easy',topic:'javascript',
    question:'Which parses a JSON string?',correct:1,
    options:['JSON.stringify()','JSON.parse()','JSON.convert()','JSON.toObject()'],
    explanation:'JSON.parse() converts a JSON string to an object.' },
  { id:11,type:'fill-blank',difficulty:'easy',topic:'javascript',
    question:'Complete the code to print to console:',
    code:'console.___("Hello World");',correct:0,
    options:['log','print','write','echo'],
    explanation:'console.log() prints to the browser console.' },
  { id:12,type:'fill-blank',difficulty:'easy',topic:'javascript',
    question:'Fill the missing keyword to declare a constant:',
    code:'___ PI = 3.14;',correct:0,
    options:['const','let','var','static'],
    explanation:'const declares a constant (immutable) variable.' },
  { id:13,type:'output',difficulty:'easy',topic:'javascript',
    question:'What does this print?',
    code:'console.log(2 + 3);',correct:2,
    options:['23','6','5','8'],
    explanation:'2 + 3 evaluates to 5.' },
  { id:14,type:'output',difficulty:'easy',topic:'javascript',
    question:'What does this print?',
    code:'console.log("Hi" + " there");',correct:1,
    options:['Hi there','Hi there','Hi+there','Error'],
    explanation:'String concatenation joins "Hi" and " there".' },
  { id:15,type:'spot-bug',difficulty:'easy',topic:'javascript',
    question:'What is wrong here?',
    code:'let x = 5\nconsole.log(X);',correct:2,
    options:['Missing semicolon','Wrong quote type','Variable name typo','console is undefined'],
    explanation:'X is not defined; JavaScript is case-sensitive, use x.' },
  { id:16,type:'fill-blank',difficulty:'easy',topic:'python',
    question:'Complete the Python print statement:',
    code:'print(___ World")',correct:1,
    options:['"Hello','\'Hello','Hello','"hello'],
    explanation:'Strings in Python use quotes: print("Hello World").' },
  { id:17,type:'output',difficulty:'easy',topic:'python',
    question:'What does this Python print?',
    code:'print(type(42))',correct:2,
    options:['<class \'str\'>','int','<class \'int\'>','number'],
    explanation:'type(42) returns <class \'int\'>.' },
  { id:18,type:'spot-bug',difficulty:'easy',topic:'web',
    question:'What is wrong?',
    code:'<img src="photo.jpg">',correct:3,
    options:['Missing alt text','src is wrong','Wrong tag','Nothing - it is valid'],
    explanation:'Valid HTML, but missing alt text for accessibility.' },
  { id:19,type:'fill-blank',difficulty:'easy',topic:'databases',
    question:'Complete the SQL query to select all:',
    code:'SELECT ___ FROM users',correct:1,
    options:['ALL','*','EVERYTHING','ALL COLUMNS'],
    explanation:'SELECT * FROM users selects all columns.' },
  { id:20,type:'output',difficulty:'easy',topic:'algorithms',
    question:'What is the result?',code:'2 + 3 * 4',correct:0,
    options:['14','20','24','9'],
    explanation:'Multiplication first: 3*4=12, then 2+12=14.' },

  // == MEDIUM ==
  { id:21,type:'multiple',difficulty:'medium',topic:'javascript',
    question:'What does typeof null return?',
    options:['null','undefined','object','boolean'],correct:2,
    explanation:'typeof null returns "object" (a legacy JS bug).' },
  { id:22,type:'fill-blank',difficulty:'medium',topic:'javascript',
    question:'Complete the arrow function:',
    code:'const add = (a,b) ___ a + b;',correct:0,
    options:['=>','->','=>>',':'],
    explanation:'Arrow functions use => syntax: (a,b) => a + b.' },
  { id:23,type:'output',difficulty:'medium',topic:'javascript',
    question:'What does this print?',
    code:'console.log(0.1 + 0.2 === 0.3)',correct:3,
    options:['true','false','0','false (floating point)'],
    explanation:'0.1+0.2=0.3000000004 due to floating point precision.' },
  { id:24,type:'spot-bug',difficulty:'medium',topic:'javascript',
    question:'What is the bug?',
    code:'if (x = 5) { console.log("yes"); }',correct:0,
    options:['Single = instead of ===','Missing semicolon','Missing braces','x not defined'],
    explanation:'x = 5 is assignment, not comparison. Use ===.' },
  { id:25,type:'multiple',difficulty:'medium',topic:'python',
    question:'Which creates a list in Python?',
    options:['[]','{}','()','<>'],correct:0,
    explanation:'Square brackets [] create a list in Python.' },
  { id:26,type:'fill-blank',difficulty:'medium',topic:'python',
    question:'Complete the list comprehension:',
    code:'squares = [x__2 for x in range(5)]',correct:1,
    options:['^','**','pow','*'],
    explanation:'** is the exponent operator in Python.' },
  { id:27,type:'output',difficulty:'medium',topic:'python',
    question:'What does this print?',
    code:'print(len("hello"))',correct:2,
    options:['4','6','5','3'],
    explanation:'len("hello") returns 5 characters.' },
  { id:28,type:'spot-bug',difficulty:'medium',topic:'web',
    question:'What is wrong with this CSS?',
    code:'.box {\n  color: red;\n  background-color: blue;\n}',correct:3,
    options:['Missing semicolon','Wrong selector','color is invalid','Nothing - it is valid'],
    explanation:'The CSS is syntactically correct.' },
  { id:29,type:'multiple',difficulty:'medium',topic:'databases',
    question:'Which SQL clause filters rows?',
    options:['ORDER BY','GROUP BY','WHERE','HAVING'],correct:2,
    explanation:'WHERE filters rows before aggregation.' },
  { id:30,type:'fill-blank',difficulty:'medium',topic:'algorithms',
    question:'What is the time complexity of binary search?',
    code:'O(___ n)',correct:0,
    options:['log','n','n^2','2^n'],
    explanation:'Binary search runs in O(log n) time.' },
  { id:31,type:'output',difficulty:'medium',topic:'javascript',
    question:'What does this print?',
    code:'console.log(typeof 42)',correct:1,
    options:['number','number','integer','float'],
    explanation:'typeof 42 returns "number".' },
  { id:32,type:'spot-bug',difficulty:'medium',topic:'general',
    question:'What is wrong?',
    code:'git pish origin main',correct:0,
    options:['Typo in command','Wrong branch','Missing flag','Nothing'],
    explanation:'"pish" should be "push": git push origin main.' },
  { id:33,type:'multiple',difficulty:'medium',topic:'javascript',
    question:'What is closure in JS?',
    options:['A syntax error','Function with access to outer scope','A built-in method','A loop type'],
    correct:1,
    explanation:'A closure is a function that retains access to its lexical scope.' },
  { id:34,type:'fill-blank',difficulty:'medium',topic:'algorithms',
    question:'Complete Big O of linear search:',
    code:'O(___)',correct:2,
    options:['1','log n','n','n^2'],
    explanation:'Linear search checks each element: O(n).' },
  { id:35,type:'output',difficulty:'medium',topic:'javascript',
    question:'What does this print?',
    code:'console.log(Boolean(0))',correct:2,
    options:['true','1','false','undefined'],
    explanation:'0 is falsy in JavaScript, so Boolean(0) is false.' },
  { id:36,type:'spot-bug',difficulty:'medium',topic:'python',
    question:'What is the bug?',
    code:'def add(x, y):\n  return x + y\nprint(add(5))',correct:1,
    options:['Wrong indentation','Missing argument','No return','Typo in print'],
    explanation:'add expects 2 args, only 1 provided.' },

  // == HARD ==
  { id:37,type:'multiple',difficulty:'hard',topic:'javascript',
    question:'What does Promise.all() do?',
    options:['Runs promises sequentially','Resolves when all promises resolve','Rejects on first resolve','Creates a new promise'],
    correct:1,
    explanation:'Promise.all() resolves when all promises in the iterable resolve.' },
  { id:38,type:'fill-blank',difficulty:'hard',topic:'javascript',
    question:'Complete the async function:',
    code:'async function getData() {\n  return ___ fetch("/api");\n}',correct:0,
    options:['await','then','wait','async'],
    explanation:'await pauses execution until the Promise settles.' },
  { id:39,type:'output',difficulty:'hard',topic:'javascript',
    question:'What does this print?',
    code:'console.log([1,2,3].map(x => x * 2))',correct:1,
    options:['[1,2,3]','[2,4,6]','[2,3,4]','[1,4,9]'],
    explanation:'map doubles each element: [2,4,6].' },
  { id:40,type:'spot-bug',difficulty:'hard',topic:'algorithms',
    question:'What is the bug?',
    code:'function fib(n) {\n  if (n <= 1) return n;\n  return fib(n-1) + fib(n-1);\n}',correct:2,
    options:['Wrong base case','Missing return','Incorrect recursion','Stack overflow'],
    explanation:'Should be fib(n-1) + fib(n-2), not two fib(n-1) calls.' },
  { id:41,type:'multiple',difficulty:'hard',topic:'python',
    question:'What is a decorator in Python?',
    options:['A design pattern','Function that modifies another function','A class method','A type hint'],
    correct:1,
    explanation:'A decorator takes a function and extends its behavior.' },
  { id:42,type:'fill-blank',difficulty:'hard',topic:'databases',
    question:'Complete the JOIN:',
    code:'SELECT * FROM users ___ JOIN orders ON users.id = orders.user_id',correct:1,
    options:['INNER','INNER','LEFT','RIGHT'],
    explanation:'INNER JOIN returns matching rows from both tables.' },
  { id:43,type:'output',difficulty:'hard',topic:'general',
    question:'What is the output?',
    code:'git log --oneline -3',correct:3,
    options:['Last 3 commits','3 branches','3 files changed','3 most recent commits (one line each)'],
    explanation:'--oneline shows one line per commit, -3 limits to 3.' },
  { id:44,type:'spot-bug',difficulty:'hard',topic:'web',
    question:'What is wrong?',
    code:'<div onclick="myFunction()">Click</div>\n// no myFunction defined anywhere',correct:0,
    options:['Function not defined','onclick is wrong','Missing parentheses','Nothing'],
    explanation:'myFunction is called but never defined, causing a ReferenceError.' },
  { id:45,type:'multiple',difficulty:'hard',topic:'algorithms',
    question:'What is the time complexity of Merge Sort?',
    options:['O(n)','O(n log n)','O(n^2)','O(log n)'],correct:1,
    explanation:'Merge Sort divides and conquers in O(n log n).' },
  { id:46,type:'fill-blank',difficulty:'hard',topic:'javascript',
    question:'Complete the reduce call to sum an array:',
    code:'[1,2,3].reduce((a,b) => ___)',correct:2,
    options:['a-b','a*b','a+b','b-a'],
    explanation:'reduce accumulates: a+b sums the array to 6.' },
  { id:47,type:'output',difficulty:'hard',topic:'python',
    question:'What does this print?',
    code:'print(list(range(0, 10, 3)))',correct:1,
    options:['[0,3,6,9]','[0,3,6,9]','[0,1,2,3,4,5,6,7,8,9]','[3,6,9]'],
    explanation:'range(0,10,3) generates 0,3,6,9.' },
  { id:48,type:'spot-bug',difficulty:'hard',topic:'javascript',
    question:'What is the bug in this React component?',
    code:'function App() {\n  const [count, setCount] = useState(0);\n  return <h1>{count}</h1>;\n}',
    options:['Missing import','count not used','setCount not called','Nothing wrong'],
    correct:0,
    explanation:'useState is not imported from React.' },
  { id:49,type:'multiple',difficulty:'hard',topic:'databases',
    question:'What is a LEFT JOIN?',
    options:['Only matching rows','All rows from left table','All rows from right table','All rows from both'],
    correct:1,
    explanation:'LEFT JOIN returns all rows from the left table, matched or not.' },
  { id:50,type:'output',difficulty:'hard',topic:'javascript',
    question:'What is the order of output?',
    code:'console.log("a");\nsetTimeout(() => console.log("b"), 0);\nconsole.log("c");',correct:3,
    options:['a,b,c','b,a,c','c,b,a','a,c,b'],
    explanation:'setTimeout runs after sync code: "a", then "c", then "b".' },
  { id:51,type:'fill-blank',difficulty:'hard',topic:'algorithms',
    question:'Complete quick sort recurrence:',
    code:'T(n) = T(k) + T(n-k-1) + O(___)',correct:2,
    options:['1','log n','n','n^2'],
    explanation:'The partition step of quicksort takes O(n).' },
  { id:52,type:'spot-bug',difficulty:'medium',topic:'general',
    question:'What is wrong?',
    code:'const http = require("fs");\nhttp.createServer()',correct:1,
    options:['require is wrong','Wrong module imported','Missing port','Nothing'],
    explanation:'fs is the filesystem module, not http. Use require("http").' },
  { id:53,type:'output',difficulty:'medium',topic:'javascript',
    question:'What does this print?',
    code:'console.log(!!"false")',correct:0,
    options:['true','false','"false"','undefined'],
    explanation:'!"false" is a non-empty string, which converts to true.' },
  { id:54,type:'fill-blank',difficulty:'easy',topic:'web',
    question:'Complete the HTML doctype:',
    code:'___DOCTYPE html>',correct:0,
    options:['<!','<?','<#','<%'],
    explanation:'HTML5 doctype is <!DOCTYPE html>.' },
  { id:55,type:'spot-bug',difficulty:'hard',topic:'python',
    question:'What is wrong?',
    code:'x = [1,2,3]\nx.add(4)\nprint(x)',correct:1,
    options:['print syntax','Lists have no add() method','Wrong variable','x not defined'],
    explanation:'Python lists use append(), not add().' },
  { id:56,type:'multiple',difficulty:'medium',topic:'algorithms',
    question:'Which is NOT a sorting algorithm?',
    options:['Merge Sort','Quick Sort','Binary Sort','Heap Sort'],correct:2,
    explanation:'There is no "Binary Sort". Binary search is search, not sort.' },
  { id:57,type:'fill-blank',difficulty:'hard',topic:'web',
    question:'Complete the CSS flex centering:',
    code:'display: flex;\njustify-content: center;\nalign-items: ___;',correct:1,
    options:['center','center','middle','flex-center'],
    explanation:'align-items: center vertically centers flex items.' },
]

const BY_ID = new Map<number, Challenge>()
ALL.forEach(c => BY_ID.set(c.id, c))

export function getChallengeById(id: number): Challenge | undefined {
  return BY_ID.get(id)
}

export function getRandomChallenge(usedIds: Set<number>, topic?: string, preferDifficulty?: string): Challenge {
  let pool = ALL
  if (topic) pool = ALL.filter(c => c.topic === topic)
  if (pool.length === 0) pool = ALL

  let available = pool
  if (preferDifficulty) {
    const preferred = pool.filter(c => c.difficulty === preferDifficulty && !usedIds.has(c.id))
    if (preferred.length > 0) available = preferred
  }

  const remaining = available.filter(c => !usedIds.has(c.id))
  if (remaining.length === 0) {
    usedIds.clear()
    return pool[Math.floor(Math.random() * pool.length)]
  }
  return remaining[Math.floor(Math.random() * remaining.length)]
}

export const TOPICS = [
  { id: 'general', label: 'General CS', description: 'Computer science fundamentals' },
  { id: 'javascript', label: 'JavaScript', description: 'JS, Node.js & frontend' },
  { id: 'python', label: 'Python', description: 'Python programming' },
  { id: 'web', label: 'Web Dev', description: 'HTML, CSS & HTTP' },
  { id: 'databases', label: 'Databases', description: 'SQL & data storage' },
  { id: 'algorithms', label: 'Algorithms', description: 'Data structures & complexity' },
] as const

export const TOTAL_CHALLENGES = ALL.length
