import { LevelConfig, LevelProgress, SceneConfig } from './types'

function sc(bgTop: string, bgBottom: string, groundColor: string, wallColor: string, elements: SceneConfig['elements'], script: SceneConfig['script']): SceneConfig {
  return { bgTop, bgBottom, groundColor, wallColor, elements, script }
}

export const ALL_LEVELS: LevelConfig[] = [
  // ═══════════ ARC 1: ESCAPE ═══════════
  {
    id: 1, name: 'The Cell', chapter: '1 — Awakening', arc: 'ESCAPE',
    enemyType: 'Prison Guard', scoreTarget: 300,
    boss: { name: 'PRISON GUARD', hp: 2, difficulty: 'easy' },
    storyIntro: 'The Cell',
    storyOutro: 'The Cell — Complete',
    sceneIntro: sc('#0a0a1a', '#1a113a', '#2a2a2a', '#3a3a3a', [
      { type: 'bars', x: 0.05, y: 0, w: 0.06, h: 1 },
      { type: 'bars', x: 0.89, y: 0, w: 0.06, h: 1 },
      { type: 'torch', x: 0.82, y: 0.12 },
      { type: 'windowHigh', x: 0.35, y: 0.08, w: 0.12, h: 0.12 },
      { type: 'bed', x: 0.1, y: 0.55, w: 0.18, h: 0.1 },
    ], [
      ['playerAnim', 'idle'],
      ['addNpc', 'guard', 0.78, 'left'],
      ['wait', 300],
      ['dialogue', 'PRISON GUARD', 'The King\'s orders — no prisoners tonight.'],
      ['dialogue', 'PRISON GUARD', 'Say your prayers, scum.'],
      ['effect', 'shake'],
      ['movePlayer', 0.42],
      ['playerAnim', 'stand'],
      ['dialogue', 'YOU', 'Not today.'],
      ['effect', 'flash'],
      ['transition'],
    ]),
    sceneOutro: sc('#0a0a1a', '#1a1a2a', '#1a1a1a', '#2a2a2a', [
      { type: 'bars', x: 0.05, y: 0, w: 0.06, h: 1 },
      { type: 'torch', x: 0.15, y: 0.12 },
      { type: 'door', x: 0.55, y: 0.2, w: 0.14, h: 0.4 },
    ], [
      ['effect', 'fadeIn'],
      ['playerAnim', 'stand'],
      ['dialogue', 'GUARD', 'The keys... take them.'],
      ['movePlayer', 0.3],
      ['effect', 'flash'],
      ['dialogue', 'YOU', 'Elena... I\'m coming.'],
      ['wait', 500],
      ['effect', 'fadeOut'],
      ['transition'],
    ]),
  },
  {
    id: 2, name: 'The Dungeon', chapter: '2 — Deeper', arc: 'ESCAPE',
    enemyType: 'Dungeon Warden', scoreTarget: 400,
    boss: { name: 'WARDEN GRIM', hp: 3, difficulty: 'easy' },
    storyIntro: 'The Dungeon',
    storyOutro: 'The Dungeon — Complete',
    sceneIntro: sc('#0a0a0a', '#1a1111', '#1a1a1a', '#2a1a1a', [
      { type: 'pillar', x: 0.12, y: 0.05, w: 0.08, h: 0.5 },
      { type: 'pillar', x: 0.8, y: 0.05, w: 0.08, h: 0.5 },
      { type: 'torch', x: 0.25, y: 0.1 },
      { type: 'torch', x: 0.75, y: 0.1 },
      { type: 'chain', x: 0.4, y: 0.1, w: 0.02, h: 0.3 },
      { type: 'chain', x: 0.6, y: 0.1, w: 0.02, h: 0.3 },
    ], [
      ['effect', 'fadeIn'],
      ['playerAnim', 'stand'],
      ['addNpc', 'warden', 0.78, 'left'],
      ['wait', 400],
      ['dialogue', 'WARDEN GRIM', 'You\'re the one from Cell 7.'],
      ['dialogue', 'WARDEN GRIM', 'The King will pay well for your head.'],
      ['effect', 'shake'],
      ['movePlayer', 0.38],
      ['playerAnim', 'walk'],
      ['dialogue', 'YOU', 'Try and take it.'],
      ['effect', 'flash'],
      ['transition'],
    ]),
    sceneOutro: sc('#0a0a0a', '#1a0a0a', '#1a1a1a', '#2a1a1a', [
      { type: 'pillar', x: 0.15, y: 0.05, w: 0.08, h: 0.5 },
      { type: 'torch', x: 0.1, y: 0.1 },
    ], [
      ['effect', 'fadeIn'],
      ['playerAnim', 'stand'],
      ['dialogue', 'PRISONER', 'The sewers... they lead to the forest.'],
      ['dialogue', 'PRISONER', 'Follow the current. It\'s your only way.'],
      ['movePlayer', 0.55],
      ['dialogue', 'YOU', 'Thank you. I won\'t forget.'],
      ['effect', 'fadeOut'],
      ['transition'],
    ]),
  },
  {
    id: 3, name: 'The Sewers', chapter: '3 — Into the Dark', arc: 'ESCAPE',
    enemyType: 'Sewer Beast', scoreTarget: 500,
    boss: { name: 'THE DEEP ONE', hp: 3, difficulty: 'medium' },
    storyIntro: 'The Sewers',
    storyOutro: 'The Sewers — Complete',
    sceneIntro: sc('#0a1a0a', '#0a0a0a', '#1a2a1a', '#2a1a1a', [
      { type: 'pipe', x: 0.1, y: 0.0, w: 0.06, h: 0.35, color: '#3a4a3a' },
      { type: 'pipe', x: 0.84, y: 0.0, w: 0.06, h: 0.35, color: '#3a4a3a' },
      { type: 'pipe', x: 0.3, y: 0.5, w: 0.4, h: 0.04, color: '#4a5a3a' },
      { type: 'torch', x: 0.5, y: 0.08, color: '#33aa33' },
    ], [
      ['effect', 'fadeIn'],
      ['playerAnim', 'idle'],
      ['addNpc', 'deepOne', 0.72, 'left'],
      ['effect', 'shake'],
      ['wait', 500],
      ['dialogue', 'THE DEEP ONE', '*low growl echoes through the tunnel*'],
      ['dialogue', 'YOU', 'Easy... just stay back...'],
      ['movePlayer', 0.4],
      ['playerAnim', 'stand'],
      ['effect', 'flash'],
      ['transition'],
    ]),
    sceneOutro: sc('#0a1a0a', '#1a2a1a', '#1a2a1a', '#2a2a2a', [
      { type: 'pipe', x: 0.45, y: 0.0, w: 0.1, h: 0.25 },
    ], [
      ['effect', 'fadeIn'],
      ['playerAnim', 'stand'],
      ['dialogue', 'YOU', '*emerges into moonlight*'],
      ['wait', 300],
      ['dialogue', 'YOU', 'The castle is behind me now.'],
      ['dialogue', 'YOU', 'The King\'s reach is long. But mine will be longer.'],
      ['effect', 'fadeOut'],
      ['transition'],
    ]),
  },

  // ═══════════ ARC 2: THE JOURNEY ═══════════
  {
    id: 4, name: 'The Dark Forest', chapter: '4 — Ambush', arc: 'THE JOURNEY',
    enemyType: 'Bandit Scouts', scoreTarget: 600,
    boss: { name: 'BANDIT LEADER', hp: 3, difficulty: 'medium' },
    storyIntro: 'The Dark Forest',
    storyOutro: 'The Dark Forest — Complete',
    sceneIntro: sc('#0a0a1a', '#1a1a2a', '#0a1a0a', '#1a2a1a', [
      { type: 'torch', x: 0.5, y: 0.55, color: '#ff8800' },
    ], [
      ['effect', 'fadeIn'],
      ['playerAnim', 'idle'],
      ['addNpc', 'bandit', 0.75, 'left'],
      ['wait', 300],
      ['dialogue', 'BANDIT LEADER', 'The King pays gold for runaways.'],
      ['dialogue', 'BANDIT LEADER', 'That one from the castle — alive, he said.'],
      ['movePlayer', 0.38],
      ['playerAnim', 'stand'],
      ['dialogue', 'YOU', 'You won\'t take me alive.'],
      ['effect', 'flash'],
      ['transition'],
    ]),
    sceneOutro: sc('#0a0a1a', '#1a1a2a', '#0a1a0a', '#1a2a1a', [
      { type: 'torch', x: 0.25, y: 0.5, color: '#ff8800' },
    ], [
      ['effect', 'fadeIn'],
      ['playerAnim', 'stand'],
      ['dialogue', 'YOU', '*picks up a map from the bandit*'],
      ['wait', 300],
      ['dialogue', 'YOU', 'The next village... Ashwick. Two days east.'],
      ['dialogue', 'YOU', 'There\'s a crest here — crossed out. I\'m not the only one.'],
      ['effect', 'fadeOut'],
      ['transition'],
    ]),
  },
  {
    id: 5, name: 'The Village', chapter: '5 — Chains', arc: 'THE JOURNEY',
    enemyType: 'King\'s Overseers', scoreTarget: 700,
    boss: { name: 'OVERSEER VARK', hp: 3, difficulty: 'medium' },
    storyIntro: 'The Village',
    storyOutro: 'The Village — Complete',
    sceneIntro: sc('#1a1a2a', '#2a2a3a', '#2a2a2a', '#3a2a2a', [
      { type: 'banner', x: 0.4, y: 0.05, w: 0.2, h: 0.15, color: '#cc0000' },
      { type: 'torch', x: 0.75, y: 0.1 },
    ], [
      ['effect', 'fadeIn'],
      ['playerAnim', 'idle'],
      ['addNpc', 'vark', 0.72, 'left'],
      ['wait', 300],
      ['dialogue', 'OVERSEER VARK', 'Another rat from the dungeon.'],
      ['dialogue', 'OVERSEER VARK', 'The King will break you like the rest.'],
      ['movePlayer', 0.4],
      ['playerAnim', 'stand'],
      ['dialogue', 'YOU', 'Where is she? Where is Elena?'],
      ['effect', 'shake'],
      ['dialogue', 'OVERSEER VARK', 'The Mountain Keep. Not that you\'ll make it.'],
      ['effect', 'flash'],
      ['transition'],
    ]),
    sceneOutro: sc('#1a1a2a', '#2a2a3a', '#2a2a2a', '#3a2a2a', [], [
      ['effect', 'fadeIn'],
      ['playerAnim', 'stand'],
      ['dialogue', 'YOU', '*holds the locket — her portrait smiles back*'],
      ['wait', 400],
      ['dialogue', 'YOU', 'She\'s alive. The Mountain Keep.'],
      ['dialogue', 'YOU', 'I\'m coming, Elena.'],
      ['effect', 'fadeOut'],
      ['transition'],
    ]),
  },
  {
    id: 6, name: 'The Mountain Pass', chapter: '6 — The Climb', arc: 'THE JOURNEY',
    enemyType: 'Mountain Giants', scoreTarget: 800,
    boss: { name: 'STONEHEART', hp: 4, difficulty: 'hard' },
    storyIntro: 'The Mountain Pass',
    storyOutro: 'The Mountain Pass — Complete',
    sceneIntro: sc('#1a1a2a', '#2a2a3a', '#3a3a3a', '#4a4a4a', [
      { type: 'windowHigh', x: 0.05, y: 0.0, w: 0.15, h: 0.2, color: '#aaccff' },
      { type: 'windowHigh', x: 0.8, y: 0.0, w: 0.15, h: 0.2, color: '#aaccff' },
    ], [
      ['effect', 'fadeIn'],
      ['playerAnim', 'idle'],
      ['addNpc', 'stoneheart', 0.72, 'left'],
      ['effect', 'shake'],
      ['wait', 500],
      ['dialogue', 'STONEHEART', 'NONE SHALL PASS.'],
      ['dialogue', 'STONEHEART', 'The King commands it.'],
      ['movePlayer', 0.38],
      ['playerAnim', 'stand'],
      ['dialogue', 'YOU', 'I don\'t take orders from tyrants.'],
      ['effect', 'flash'],
      ['transition'],
    ]),
    sceneOutro: sc('#1a1a2a', '#2a2a3a', '#3a3a3a', '#4a4a4a', [
      { type: 'windowHigh', x: 0.02, y: 0.0, w: 0.2, h: 0.25, color: '#aaccff' },
    ], [
      ['effect', 'fadeIn'],
      ['playerAnim', 'stand'],
      ['dialogue', 'YOU', '*the pass is clear*'],
      ['wait', 300],
      ['dialogue', 'YOU', 'There it is... the Mountain Keep.'],
      ['dialogue', 'YOU', 'She\'s inside. I\'m almost there.'],
      ['effect', 'fadeOut'],
      ['transition'],
    ]),
  },

  // ═══════════ ARC 3: THE CASTLE ═══════════
  {
    id: 7, name: 'The Courtyard', chapter: '7 — Infiltration', arc: 'THE CASTLE',
    enemyType: 'Castle Guards', scoreTarget: 900,
    boss: { name: 'GATE COMMANDER', hp: 4, difficulty: 'hard' },
    storyIntro: 'The Courtyard',
    storyOutro: 'The Courtyard — Complete',
    sceneIntro: sc('#1a1a2a', '#2a2a4a', '#2a2a2a', '#3a3a3a', [
      { type: 'banner', x: 0.05, y: 0.0, w: 0.15, h: 0.18, color: '#cc0000' },
      { type: 'banner', x: 0.8, y: 0.0, w: 0.15, h: 0.18, color: '#cc0000' },
      { type: 'torch', x: 0.3, y: 0.1 },
      { type: 'torch', x: 0.7, y: 0.1 },
    ], [
      ['effect', 'fadeIn'],
      ['playerAnim', 'idle'],
      ['addNpc', 'commander', 0.74, 'left'],
      ['wait', 300],
      ['dialogue', 'GATE COMMANDER', 'Intruder! Seal the gates!'],
      ['effect', 'shake'],
      ['movePlayer', 0.4],
      ['playerAnim', 'stand'],
      ['dialogue', 'YOU', 'I didn\'t come this far to stop now.'],
      ['effect', 'flash'],
      ['transition'],
    ]),
    sceneOutro: sc('#1a1a2a', '#2a2a4a', '#2a2a2a', '#3a3a3a', [], [
      ['effect', 'fadeIn'],
      ['playerAnim', 'stand'],
      ['dialogue', 'YOU', '*the inner gate is open*'],
      ['wait', 300],
      ['dialogue', 'YOU', 'The grand staircase... she\'s close.'],
      ['effect', 'fadeOut'],
      ['transition'],
    ]),
  },
  {
    id: 8, name: 'The Great Hall', chapter: '8 — The Captain', arc: 'THE CASTLE',
    enemyType: 'Elite Guard', scoreTarget: 1000,
    boss: { name: 'CAPTAIN DRAVEN', hp: 4, difficulty: 'hard' },
    storyIntro: 'The Great Hall',
    storyOutro: 'The Great Hall — Complete',
    sceneIntro: sc('#1a0a0a', '#2a1a1a', '#2a1a1a', '#3a2a2a', [
      { type: 'pillar', x: 0.08, y: 0.0, w: 0.08, h: 0.55 },
      { type: 'pillar', x: 0.84, y: 0.0, w: 0.08, h: 0.55 },
      { type: 'torch', x: 0.2, y: 0.12 },
      { type: 'torch', x: 0.8, y: 0.12 },
      { type: 'banner', x: 0.4, y: 0.02, w: 0.2, h: 0.2, color: '#8B0000' },
    ], [
      ['effect', 'fadeIn'],
      ['playerAnim', 'idle'],
      ['addNpc', 'draven', 0.72, 'left'],
      ['wait', 400],
      ['dialogue', 'CAPTAIN DRAVEN', 'You\'ve come far, prisoner.'],
      ['dialogue', 'CAPTAIN DRAVEN', 'But this is where you fall.'],
      ['movePlayer', 0.38],
      ['playerAnim', 'stand'],
      ['effect', 'shake'],
      ['dialogue', 'YOU', 'Where is she, Draven?'],
      ['dialogue', 'CAPTAIN DRAVEN', 'Above. Not that you\'ll reach her.'],
      ['effect', 'flash'],
      ['transition'],
    ]),
    sceneOutro: sc('#1a0a0a', '#2a1a1a', '#2a1a1a', '#3a2a2a', [
      { type: 'pillar', x: 0.4, y: 0.0, w: 0.08, h: 0.55 },
    ], [
      ['effect', 'fadeIn'],
      ['playerAnim', 'stand'],
      ['dialogue', 'CAPTAIN DRAVEN', 'She\'s alive... the King keeps her in the tower.'],
      ['dialogue', 'CAPTAIN DRAVEN', 'He wants you to come. It\'s a trap.'],
      ['movePlayer', 0.55],
      ['dialogue', 'YOU', 'I know. I don\'t care.'],
      ['effect', 'fadeOut'],
      ['transition'],
    ]),
  },
  {
    id: 9, name: 'The Throne Room', chapter: '9 — The King', arc: 'THE CASTLE',
    enemyType: 'Royal Sorcerer', scoreTarget: 1200,
    boss: { name: 'THE KING', hp: 5, difficulty: 'hard' },
    storyIntro: 'The Throne Room',
    storyOutro: 'Code Run — Complete',
    sceneIntro: sc('#1a0a1a', '#2a0a2a', '#2a1a2a', '#3a1a3a', [
      { type: 'throne', x: 0.65, y: 0.15, w: 0.18, h: 0.35, color: '#ffd700' },
      { type: 'pillar', x: 0.05, y: 0.0, w: 0.08, h: 0.6 },
      { type: 'pillar', x: 0.87, y: 0.0, w: 0.08, h: 0.6 },
      { type: 'banner', x: 0.3, y: 0.0, w: 0.12, h: 0.22, color: '#8B0000' },
      { type: 'banner', x: 0.58, y: 0.0, w: 0.12, h: 0.22, color: '#8B0000' },
      { type: 'torch', x: 0.15, y: 0.12, color: '#ff2222' },
      { type: 'torch', x: 0.75, y: 0.12, color: '#ff2222' },
    ], [
      ['effect', 'fadeIn'],
      ['playerAnim', 'stand'],
      ['addNpc', 'king', 0.72, 'left'],
      ['addNpc', 'elena', 0.55, 'left'],
      ['wait', 500],
      ['dialogue', 'THE KING', 'I wondered when you\'d arrive.'],
      ['dialogue', 'THE KING', 'I\'ve watched you climb through every level of my kingdom.'],
      ['dialogue', 'THE KING', 'Solve my final puzzle, and she goes free.'],
      ['effect', 'shake'],
      ['movePlayer', 0.35],
      ['dialogue', 'ELENA', '*she shakes her head, eyes pleading*'],
      ['dialogue', 'YOU', 'I\'m not leaving without her.'],
      ['dialogue', 'THE KING', 'Then die trying.'],
      ['effect', 'flash'],
      ['transition'],
    ]),
    sceneOutro: sc('#1a0a1a', '#2a0a2a', '#1a1a1a', '#2a1a2a', [], [
      ['effect', 'fadeIn'],
      ['playerAnim', 'stand'],
      ['wait', 500],
      ['dialogue', '', 'The King falls. The chains of light shatter.'],
      ['dialogue', 'ELENA', '*she runs to you*'],
      ['wait', 300],
      ['dialogue', 'YOU', 'Elena... it\'s over.'],
      ['dialogue', 'SOLDIER', 'The castle is ours! The people have risen!'],
      ['wait', 400],
      ['dialogue', '', 'You walk out of the Throne Room together, into the dawn.'],
      ['wait', 600],
      ['dialogue', '', 'CODE RUN — COMPLETE'],
      ['wait', 800],
      ['effect', 'fadeOut'],
      ['transition'],
    ]),
  },
]

const STORAGE_KEY = 'code_level_progress'

export const ENDING_SCENE: SceneConfig = {
  bgTop: '#1a0a1a',
  bgBottom: '#2a1a2a',
  groundColor: '#1a1a1a',
  wallColor: '#2a1a2a',
  elements: [
    { type: 'torch', x: 0.08, y: 0.12 },
    { type: 'torch', x: 0.92, y: 0.12 },
    { type: 'windowHigh', x: 0.3, y: 0.05, w: 0.12, h: 0.15, color: '#ffdd88' },
    { type: 'windowHigh', x: 0.58, y: 0.05, w: 0.12, h: 0.15, color: '#ffdd88' },
  ],
  script: [
    ['effect', 'fadeIn'],
    ['wait', 600],
    ['playerAnim', 'stand'],
    ['addNpc', 'elena', 0.42, 'right'],
    ['addNpc', 'guard', 0.25, 'right'],
    ['addNpc', 'commander', 0.6, 'left'],
    ['dialogue', '', 'The castle falls. The kingdom breathes again.'],
    ['wait', 400],
    ['dialogue', 'ELENA', 'You came back for me. Through all of it.'],
    ['movePlayer', 0.35],
    ['dialogue', 'YOU', 'I told you I would.'],
    ['wait', 300],
    ['effect', 'flash'],
    ['dialogue', 'COMMANDER', 'The people are with you. The King\'s reign is over.'],
    ['wait', 300],
    ['effect', 'fadeOut'],
    ['wait', 400],
    ['effect', 'fadeIn'],
    ['dialogue', '', 'Months later...'],
    ['wait', 500],
    ['effect', 'fadeOut'],
    ['wait', 400],
    ['effect', 'fadeIn'],
    ['playerAnim', 'idle'],
    ['movePlayer', 0.42],
    ['dialogue', 'ELENA', 'What will you do now?'],
    ['dialogue', 'YOU', 'Build something new.'],
    ['wait', 300],
    ['dialogue', '', 'A kingdom of code. Of logic. Of freedom.'],
    ['wait', 500],
    ['effect', 'fadeOut'],
    ['wait', 400],
    ['effect', 'fadeIn'],
    ['dialogue', '', '★ ESCAPE — ARC COMPLETE ★'],
    ['wait', 300],
    ['dialogue', '', '★ THE JOURNEY — ARC COMPLETE ★'],
    ['wait', 300],
    ['dialogue', '', '★ THE CASTLE — ARC COMPLETE ★'],
    ['wait', 500],
    ['dialogue', '', 'All nine chapters. All nine puzzles.'],
    ['wait', 400],
    ['dialogue', '', 'Every line of code brought you home.'],
    ['wait', 600],
    ['dialogue', '', '✧ THE END ✧'],
    ['wait', 1000],
    ['effect', 'fadeOut'],
    ['transition'],
  ],
}

export function getLevelProgress(): LevelProgress {
  try {
    const raw = localStorage.getItem(STORAGE_KEY)
    if (raw) return JSON.parse(raw)
  } catch {}
  return { unlockedUpTo: 1, completed: [], stars: {} }
}

export function saveLevelProgress(p: LevelProgress) {
  try { localStorage.setItem(STORAGE_KEY, JSON.stringify(p)) } catch {}
}

export function isLevelUnlocked(levelId: number, progress: LevelProgress): boolean {
  return levelId <= progress.unlockedUpTo
}
